In [1]:
#import numpy module
import numpy as np

In [2]:
data1=[1,2,3,4] #list 
arr1=np.array(data1) # 1D array
data2=[range(1,5), range(5,9)] #list of list
arr2=np.array(data2) #2D array
print(data1)
print(arr1)
print(data2)
print(arr2)

[1, 2, 3, 4]
[1 2 3 4]
[range(1, 5), range(5, 9)]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
arr2.tolist() ##convert array back to list

[[1, 2, 3, 4], [5, 6, 7, 8]]

## create special array

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones(10) # cerate array of 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.linspace(0,1,num=5) # 0 to 1 (inclusive )with 5 points

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.logspace(0,3,4)# 10^0 to 10^3 with 4 points

array([   1.,   10.,  100., 1000.])

In [9]:
int_array=np.arange(5) #return range of array(not a list)

In [10]:
flaot_array=int_array.astype(float) #changes the array element type to float

## examing array

In [11]:
print("data type of arr1 is ", arr1.dtype)
print("data type of arr2 is :", arr2.dtype)
print("dimension of arr1 is :", arr1.ndim)
print("dimension of arr2 is : ", arr2.ndim)
print("shape of array, rows and columns is: ", arr2.shape)

int32
int32
2
(2, 4)
8
2


## Reshaping

In [12]:
arr=np.arange(10,dtype=float).reshape((5,2)) #creates array with 10 elements and reshape into 5 rows and 2 column

In [13]:
print(arr.shape) # prints the shape of array
print(arr.reshape(5,2)) # reshapes and prints  shape of array

(5, 2)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


### Add an axis

In [14]:
a=np.array([0,1])  # creates an array
a_col=a[:,np.newaxis] # creates new array by reshaping into column 
print(a_col) 
## a_col=a[:,None]

[[0]
 [1]]


## Transpose

In [15]:
a_col.T # transposes an array

array([[0, 1]])

## Flatten :always return a flat copy of the original array

In [16]:
arr_flt=arr.flatten() # returns a flat copy of the original array
arr_flt[0]=33 # changes the first element 
print(arr_flt) 
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


## Ravel :Return a view of the original array 

In [17]:
arr_flt=arr.ravel() # returns the view of an array
print(arr_flt)
arr_flt[0]=33 # changes the first element 
print(arr_flt)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]


## stack array

In [18]:
a=np.array([0,1]) # creates an array a
b=np.array([2,3]) # creates an array b

In [19]:
ab=np.stack((a,b)).T # joins array a and b and transposes the result array
##np.hstack(a[:,None],b[:,None])

In [20]:
print(ab)

[[0 2]
 [1 3]]


## selection

In [21]:
arr=np.arange(10,dtype=float).reshape((2,5))
print(arr[0]) #oth element (slice like a list)
print(arr[0,3]) #row 0,column 3: return 4
print(arr[0][3]) # alternative syntax

[0. 1. 2. 3. 4.]
3.0
3.0


## slicing

In [22]:
print(arr[0, :])    # row 0: returns 1d array([1, 2, 3, 4])
print(arr[:, 0])    # column 0: returns 1d array
print(arr[:, :3])   # columns strictly before index 2 ( first columns )
print(arr[:, 2:])   # columns after index 2 included
arr2 = arr[:, 1:4]  # columns between index 1 (included) and 4 (excluded)
print(arr2)
arr2[0, 0] = 33
print(arr2)
print(arr)
print("Reversed row", arr[0, ::-1]) #reverse order

[0. 1. 2. 3. 4.]
[0. 5.]
[[0. 1.]
 [5. 6.]]
[[2. 3. 4.]
 [7. 8. 9.]]


[[1. 2. 3.]
 [6. 7. 8.]]


In [24]:
arr2[0,0]=33
print(arr2)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [25]:
print(arr[0,::-1]) 

[ 4.  3.  2. 33.  0.]


In [26]:
## fancy indexing: integer or boolean array indexing


In [27]:
arr2=arr[:,[1,2,3]]

In [28]:
print(arr2)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [29]:
arr2[0,0]=44

In [30]:
print(arr2)

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [31]:
print(arr)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [32]:
#Boolean array indexing

In [33]:
arr2=arr[arr>5] # return a copy. 1d array with the element value greater than 5

In [34]:
print(arr2)

[33.  6.  7.  8.  9.]


In [35]:
arr2[0]=44

In [36]:
print(arr2)
print(arr)

[44.  6.  7.  8.  9.]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [37]:
arr[arr>5]=0
print(arr)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [38]:
names=np.array(["Bob","joe","will","Bob"])
names=="Bob" # returns a boolean array
names[names !="Bob"] # logical selection if name is not equal to Bob

array(['joe', 'will'], dtype='<U4')

In [ ]:
(names == 'Bob') | (names == 'Will') #if name is Bob or Will it returns true else false


In [39]:
names[names !="Bob"]="joe" # if name is not equal to bob replace element by joea


In [40]:
np.unique(names) # returns unique element of names array

array(['Bob', 'joe'], dtype='<U4')

In [41]:
#vectorized operations

In [42]:
nums=np.arange(5) # creates numpy array called nums
nums*10 # multiplies each element by 10
nums=np.sqrt(nums) # returns squre root of each element
np.ceil(nums) # also floor, rint (round to nearest int)
np.isnan(nums) # checks for NaN
nums+np.arange(5) # add element-wise
np.maximum(nums,np.array([1,-2,3,-4,5])) # compare element-wise and return the array with maximum

# computing Euclidean distance between 2 vectors
vec1=np.random.randn(10) # creates an array with random number 
vec2=np.random.randn(10)# creates an array with random number 
dist=np.sqrt(np.sum(vec1-vec2)**2) # forula to calculate Euclidean distance
print(dist)
rnd=np.random.randn(4,2) # creates 4x2 array with random number 
rnd.mean() # return mean of an array
rnd.std() # returns standard deviation of an array
rnd.argmin() # returns index of minimum element
rnd.sum() # returns the sum of elements of an array
rnd.sum(axis=0) # returns sum of columns
rnd.sum(axis=1) # returns sum of rows

(rnd>0).any() # checks if any value is true
(rnd>0).all() # checks if all value is true

# random numbers
np.random.seed(12234)  # set the seed
print(np.random.rand(2,3)) # 2x3 matrix in  [0, 1]
print(np.random.randn(10)) # random normals ( mean 0, sd 1)
print(np.random.randint(0,2,10)) # 10 randomly picked 0 or 1

7.004523776273183
[[0.00630595 0.20303476 0.76478993]
 [0.55513384 0.74358546 0.93777808]]
[-2.79962074e-01  1.31281104e+00 -9.27155784e-01 -4.01302169e-01
 -2.31085929e+00 -2.08460156e+00  4.59241643e-01  1.62191344e+00
  1.94515120e-01 -2.08631547e-03]
[0 0 0 1 1 0 1 1 1 1]


## Boardcasting

In [43]:
# creating 4 x 3 matric
a=np.array([[0,0,0],
            [10,10,10],
            [20,20,20],
            [30,30,30]
           ])
b=np.array([0,1,2]) # creating 1d array

In [44]:
print(a+b) # adding array a and b and printing the result

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# Assignment

In [45]:
# creating random array  X with 4 rows and 2 column 
X=np.random.rand(4,2)

In [46]:
print(X) # printing array X

[[0.38180717 0.81368435]
 [0.45600361 0.98253171]
 [0.65195391 0.89018285]
 [0.69723802 0.04095198]]


In [47]:
print(X.argmin(axis=0)) # finding the row index of the minimum value

[0 3]


In [48]:
'''
function: standardize
work: standardizes an array
return: an array whose columns are centered and scaled(by std-dev)

'''
def standardize(X):
    standardized_l = (X-X.mean())/X.std() # formula for standerdization
    print(standardized_l)

In [49]:
standardize(X) # calling function

[[-0.80479843  0.69022724]
 [-0.54795322  1.27472475]
 [ 0.13036631  0.95504144]
 [ 0.28712592 -1.98473401]]
