In [0]:
from __future__ import print_function
import numpy as np 


#Create n-dimentional array 

#1D array
data_1 = [1,2,3,4,5]
arr1 = np.array(data_1)
print("1D array: ", arr1)



#2D array
data_2 = [range(1,5), range(5,9)] 
arr2 = np.array(data_2) 
print("2D array: ", arr2) #[[1 2 3 4] [5 6 7 8]]
print("2D array as list:  ", arr2.tolist()) #[[1 2 3 4], [5 6 7 8]] converting an array to list


#3D array
data_3 = [range(1,5), range(5,9), range(9,13)] 
arr3 = np.array(data_3) 
print("3D array: ", arr3) 
print("3D array as list ", arr3.tolist()) 




#Create Special array 



print("np.zeros(10): ",np.zeros(10)  ) # prints a non empty array with value 0
print("np.zeros((3,6))", np.zeros((3,6))) #prints a 3*6 matix with zeros
print("np.ones(10): ", np.ones(10)  ) # prints a non empty array with value 1
print("np.linspace(0,1,5): ",np.linspace(0,1,5)) # prints the values between 0 to 1 with 5 intervals
print("np.logspace(0,3,4): ",np.logspace(0,3,5)) #10̈́^0 to 10^3 with 5 intervals



int_array = np.arange(5)
print("int_array = ", int_array)
print("float_array = ",int_array.astype(float))

#using range
for i in range(0,5):
    print(i)


#Examining array: 


print("arr1.dtype:  ", arr1.dtype) 
print("arr2.dtype:  ", arr2.dtype) 
print("arr2.dim:  ", arr2.ndim) 
print("arr2.shape:  ", arr2.shape) 
print("arr3.shape:  ", arr3.shape) 


print("ar2: ", arr2)
print("arr2.size: ", arr2.size)
print("len(arr2): ", len(arr2))



# Reshaping 


arr = np.arange(10, dtype = float).reshape((2,5))
print("arr: \n", arr)
print("arr.shape: \n ", arr.shape)
print("arr.reshape: \n ", arr.reshape(5,2))



# Reshaping 


a = np.array([0,1,2,3,4])
print("a:", a)
a_col  = a[:,np.newaxis]
print("a_col: ", a_col)

a_col = a[:,None]
print("a_col: ", a_col)

#Transpose 
print("Transpose: ", a_col.T)




1D array:  [1 2 3 4 5]
2D array:  [[1 2 3 4]
 [5 6 7 8]]
2D array as list:   [[1, 2, 3, 4], [5, 6, 7, 8]]
3D array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3D array as list  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
np.zeros(10):  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
np.zeros((3,6)) [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
np.ones(10):  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.linspace(0,1,5):  [0.   0.25 0.5  0.75 1.  ]
np.logspace(0,3,4):  [   1.            5.62341325   31.6227766   177.827941   1000.        ]
int_array =  [0 1 2 3 4]
float_array =  [0. 1. 2. 3. 4.]
0
1
2
3
4
arr1.dtype:   int64
arr2.dtype:   int64
arr2.dim:   2
arr2.shape:   (2, 4)
arr3.shape:   (3, 4)
ar2:  [[1 2 3 4]
 [5 6 7 8]]
arr2.size:  8
len(arr2):  2
arr: 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
arr.shape: 
  (2, 5)
arr.reshape: 
  [[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
a: [0 1 2 3 4]
a_col:  [[0]
 [1]
 [2]
 [3]
 [4]]
a_col:  [[0]
 [1]
 [2]
 [3]
 [4]]
Transpose:  [[0 1 2 3 4]]


In [0]:
# Flatten:  always return a flat copy of the original array 

print("Flatten output: ")
print("arr: ", arr)

arr_flt = arr.flatten()
arr_flt[0] = 33 # add 33 in the 0th index

print("arr_flt: ", arr_flt)
print("arr: ", arr)

# Ravel: return a value of the original of the flattened array 

print("Ravel output: ")
arr_flt2 = arr.ravel()
arr_flt2[0] = 33
print("arr_flt2: ", arr_flt2)
print("arr ", arr)

Flatten output: 
arr:  [[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
arr_flt:  [33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
arr:  [[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
Ravel output: 
arr_flt2:  [33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
arr  [[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
# Stack array 



a = np.array([0,1])
b = np.array([2,3])
print("a", a)
print("b", b)
ab_shape = np.stack((a,b)).shape # shows shape 
print("Shape: ", ab_shape)
ab = np.stack((a,b)).T # converting rows in the colomn 
print("Transpose: ", ab)

a [0 1]
b [2 3]
Shape:  (2, 2)
Transpose:  [[0 2]
 [1 3]]


In [0]:
# Selection 


arr5 = np.arange(10, dtype = float).reshape((2,5))
print("arr5: ", arr5)
print("arr5[0]: ",arr5[0])
print("arr5[0, 4]:", arr5[0, 4]) # row 0, column 4 > returns 4 
print("arr5[0][4]:", arr5[0][4]) # row 0, column 4 > returns 4 - alternative systax 

arr5:  [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
arr5[0]:  [0. 1. 2. 3. 4.]
arr5[0, 4]: 4.0
arr5[0][4]: 4.0


In [0]:
#Slicing 


print("arr5: \n", arr5)
print("arr5[0, :]: \n", arr5[0, :])
print("arr5[:,0]: \n", arr5[:,0])
print("arr5[:, :2]: \n", arr5[:, :2])
print("arr5[:, 2:]: \n", arr5[:, 2:])
arr6 = arr5[:, 1:4]
print("arr5[:, 1:4] \n", arr6)



# Reverse order 

print("Reverse 1: ", arr5[0, ::-1] ) # 
print("Reverse 2: ", arr5[1, ::-1] ) # 
print("Reverse 3: ", arr5[ ::-1] ) # 

arr5: 
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
arr5[0, :]: 
 [0. 1. 2. 3. 4.]
arr5[:,0]: 
 [0. 5.]
arr5[:, :2]: 
 [[0. 1.]
 [5. 6.]]
arr5[:, 2:]: 
 [[2. 3. 4.]
 [7. 8. 9.]]
arr5[:, 1:4] 
 [[1. 2. 3.]
 [6. 7. 8.]]
Reverse 1:  [4. 3. 2. 1. 0.]
Reverse 2:  [9. 8. 7. 6. 5.]
Reverse 3:  [[5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4.]]


In [0]:
#Fancy Indexing  - returns a copy, not a view 

print("arr5: \n", arr5)
print(" arr[:, [1,2,4]]: \n",arr[:, [1,2,4]] ) # print everything from colomn index 1, 2, 4 

arr5[0,0] = 45

print("arr5: \n", arr5)

print("arr: \n", arr)


arr5: 
 [[45.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
 arr[:, [1,2,4]]: 
 [[1. 2. 4.]
 [6. 7. 9.]]
arr5: 
 [[45.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
arr: 
 [[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
# Booloean array indexing 


print(arr5)
arr7 = arr5[arr5 > 5] # printing all number largerer than 5 
print("\n")
print(arr7)
arr7[1] = 97
print("\n")
print(arr7)


# replacing all the value greater than 5 

arr7[arr7 > 5] = 0
print("\n ", arr7)

[[45.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


[45.  6.  7.  8.  9.]


[45. 97.  7.  8.  9.]

  [0. 0. 0. 0. 0.]


In [0]:
#Boolean array indexing.... 


names = np.array(['anik','sileshi','peter','rakesh'])
print(names == 'anik') # [ True False False False]
names[names != 'anik']
(names == 'anik') | (names == 'peter')
names[names != 'anik' ] = 'sileshi'
np.unique(names)


[ True False False False]


array(['anik', 'sileshi'], dtype='<U7')

In [0]:
#Vectorized operarions 

nums = np.arange(5)
print("np.arange(5): ", nums ) # [0 1 2 3 4]
print("nums * 10 :", nums*10 ) # [ 0 10 20 30 40]
nums = np.sqrt(nums)
print("sqrt: ", nums) # [0.         1.         1.41421356 1.73205081 2.        ]
print("Ceil: ", np.ceil(nums)) # [0. 1. 2. 2. 2.]
print("isNaN: ", np.isnan(nums)) # Not a number - [False False False False False]
print("nums + np.arange(5):  ", nums + np.arange(5)) # [0.         2.         3.41421356 4.73205081 6.        ]
print("np.maximum: ", np.maximum(nums, np.array([1,-2, 3, -4, 5 ]))) #  [1.         1.         3.         1.73205081 5.        ]

np.arange(5):  [0 1 2 3 4]
nums * 10 : [ 0 10 20 30 40]
sqrt:  [0.         1.         1.41421356 1.73205081 2.        ]
Ceil:  [0. 1. 2. 2. 2.]
isNaN:  [False False False False False]
nums + np.arange(5):   [0.         2.         3.41421356 4.73205081 6.        ]
np.maximum:  [1.         1.         3.         1.73205081 5.        ]


In [0]:
#compute 
vector1 = np.random.randn(10)
print(vector1)
vector2 = np.random.randn(10)
dist = np.sqrt(np.sum((vector1 - vector2) ** 2))
print(dist)

[-0.09508749  0.02379388 -0.18478749  0.38640911  0.46374574  0.40530762
 -0.49548321 -0.00946938 -0.27789627 -0.42438041]
5.65525619713766


In [0]:

#math..

rnd = np.random.randn(4,2) # random in form of 4x2 array 
print("random 4x2 format: ", rnd)
print("random mean: ", rnd.mean())
print("random std: ", rnd.std())
print("random argmin: ", rnd.argmin()) #shows the position 
print("random sum: ", rnd.sum())
print("random sum(axis=0): ", rnd.sum(axis=0)) # column
print("random sum(axis=1): ", rnd.sum(axis=1)) # row 





random 4x2 format:  [[-0.67641501 -0.81116262]
 [-0.36642584 -0.42755008]
 [ 1.02837214  0.10413813]
 [-1.14609236 -0.6001503 ]]
random mean:  -0.3619107424122866
random std:  0.6251855746069955
random argmin:  6
random sum:  -2.895285939298293
random sum(axis=0):  [-1.16056107 -1.73472486]
random sum(axis=1):  [-1.48757763 -0.79397592  1.13251027 -1.74624266]


In [0]:


#Methods for boolean array

print("rnd: ", rnd)
print("rnd > 0: ", (rnd > 0).sum()) # count the positive values 
print("rnd > 0: ", (rnd > 0).any()) # check if any value is true 
print("rnd > 0: ", (rnd > 0).all()) # check if all values are true 



# random numbers: 
print("Random numbers: ")

print(np.random.seed(12234)) # set the seed
print(np.random.rand(2,3)) # 2 x 3 matrix 
print(np.random.randn(10)) # mean normals 
print(np.random.randint(0,6,10)) # 10 randomly picked 0,1,2,3,4,5




rnd > 0  2


In [0]:
a = np.array([[0, 0, 0], [10 ,10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [0]:
X = np.random.randn(4,2)
print(X)
print(X.argmin())
print(X[:,0])
print(X[:,0].argmin())
print(X[:,1])
print(X[:,1].argmin())

[[-0.93529347  0.47375006]
 [ 1.23988275  0.88721125]
 [-0.35339309  1.96213891]
 [-0.66554641 -0.20451016]]
0
[-0.93529347  1.23988275 -0.35339309 -0.66554641]
0
[ 0.47375006  0.88721125  1.96213891 -0.20451016]
3


In [0]:
standardize= (X-X.mean()) / X.std() # This is done with a standard formula given for standard deviation
print(standardize)
  

[[-1.30623555  0.18308945]
 [ 0.9928732   0.62010794]
 [-0.69118089  1.75628052]
 [-1.02111942 -0.53381524]]


In [0]:
from mlxtend.preprocessing import standardize # This is done using a built-in function called standarize
standardize(X, columns=[0, 1])

array([[-0.89609879, -0.38911863],
       [ 1.67976686,  0.13682708],
       [-0.20700647,  1.50419504],
       [-0.57666159, -1.25190349]])

Page 7:

The image in page 7 explains the way to add different dimensional arrays. For example, we can add 3D array only if another array is also 3D. We cannot add 3D with another 1D array. To add, 1D array with 3D, we must need to convert 1D array to 3D array. The first picture adds 3D array with another 3D array. The second picture adds 3D array with 1D array after converting it to the 3D array. In the third picture, both were 1D array and so we converted both into 3D array first. In the end, the output is same 3D array.

5 commands from Scipy: 
* ndarray.real: It shows the real part of an array
* ndarray.imag: It shows the imaginary part of an array
* ndarray.sort: It sort an array
* ndarray.round: Return a with each element rounded to the given number of decimals. It may be very * useful when we don’t need the fraction of data.
* numpy.mod: It returns the element wise reminder of the division
